# Generated by Django 3.1.6 on 2021-02-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('eqId', models.AutoField(primary_key=True, serialize=False)),
                ('eqState', models.IntegerField(default=0)),
            ],
        ),
    ]
