# Generated by Django 3.1.6 on 2021-02-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labDemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='eqState',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
