# Generated by Django 3.1.6 on 2021-02-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labDemo', '0003_auto_20210217_1250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
