# Generated by Django 3.1.6 on 2021-02-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labDemo', '0004_delete_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('eqId', models.AutoField(primary_key=True, serialize=False)),
                ('eqName', models.CharField(max_length=20)),
                ('eqState', models.IntegerField(default=0)),
            ],
        ),
    ]
