# Generated by Django 3.1.6 on 2021-02-17 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labDemo', '0005_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerInfo',
            fields=[
                ('perInfoId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('telephone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False)),
                ('roleNum', models.CharField(max_length=10)),
                ('roleName', models.CharField(max_length=50)),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('perInfoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labDemo.perinfo')),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labDemo.role')),
            ],
        ),
    ]
