# Generated by Django 3.1.6 on 2021-02-17 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labDemo', '0007_auto_20210217_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpData',
            fields=[
                ('expDataId', models.AutoField(primary_key=True, serialize=False)),
                ('expName', models.CharField(max_length=20)),
                ('expContent', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pjId', models.AutoField(primary_key=True, serialize=False)),
                ('pjNum', models.CharField(max_length=20)),
                ('pjName', models.CharField(max_length=20)),
                ('responPer', models.CharField(max_length=20)),
                ('pjState', models.IntegerField(default=0)),
                ('checkPer', models.CharField(max_length=20)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='eqId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='设备编号'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='eqName',
            field=models.CharField(max_length=20, unique=True, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='eqState',
            field=models.IntegerField(choices=[(0, '空闲'), (-1, '维修/保养'), (1, '已借出')], verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='perinfo',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='perinfo',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='电邮'),
        ),
        migrations.AlterField(
            model_name='perinfo',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='perinfo',
            name='perInfoId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='个人信息编号'),
        ),
        migrations.AlterField(
            model_name='perinfo',
            name='telephone',
            field=models.CharField(max_length=11, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='role',
            name='remark',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='role',
            name='roleId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='用户组编号'),
        ),
        migrations.AlterField(
            model_name='role',
            name='roleName',
            field=models.CharField(max_length=50, verbose_name='用户组名'),
        ),
        migrations.AlterField(
            model_name='role',
            name='roleNum',
            field=models.CharField(max_length=10, verbose_name='用户组'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=16, verbose_name='密码'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reId', models.AutoField(primary_key=True, serialize=False)),
                ('reState', models.IntegerField(default=0)),
                ('approvalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labDemo.user')),
                ('rePer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labDemo.perinfo')),
            ],
        ),
    ]
