# Generated by Django 3.1.6 on 2021-02-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labDemo', '0008_auto_20210217_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='approvalId',
            new_name='approvalPer',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='eqState',
            field=models.IntegerField(choices=[(0, '空闲'), (-1, '维修/保养'), (1, '已借出')], default=0, verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='预约编号'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reState',
            field=models.IntegerField(choices=[(0, '预约中'), (-1, '拒绝'), (1, '批准'), (2, '已结束')], default=0, verbose_name='预约状态'),
        ),
    ]
