# Generated by Django 3.1.6 on 2021-03-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labDemo', '0011_auto_20210317_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='endTime',
            field=models.DateTimeField(null=True, verbose_name='结束时间'),
        ),
    ]
