# Generated by Django 3.1.6 on 2021-03-17 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('labDemo', '0012_reservation_endtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='applyTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='申请时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='checkTime',
            field=models.DateTimeField(null=True, verbose_name='审批时间'),
        ),
    ]
