# Generated by Django 3.1.6 on 2021-03-17 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labDemo', '0013_auto_20210317_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='checkTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批时间'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 15, 2, 52, 343461), verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 15, 2, 52, 343461), verbose_name='开始时间'),
        ),
    ]
