# Generated by Django 3.1.6 on 2021-05-12 15:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labDemo', '0014_auto_20210317_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reEquip',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='labDemo.equipment', verbose_name='预约器材'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 15, 51, 52, 846547), verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 15, 51, 52, 846547), verbose_name='开始时间'),
        ),
    ]
