# Generated by Django 3.1.6 on 2021-05-12 16:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('labDemo', '0015_auto_20210512_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='endTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reEquip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labDemo.equipment', to_field='eqName', verbose_name='预约器材'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='startTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间'),
        ),
    ]
