# Generated by Django 3.1.6 on 2021-05-21 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labDemo', '0016_auto_20210512_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='perinfo',
            name='perId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='用户ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perinfo',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='电子邮件'),
        ),
    ]
