# Generated by Django 3.1.6 on 2021-05-22 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labDemo', '0017_auto_20210521_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perinfo',
            name='email',
            field=models.CharField(max_length=30, verbose_name='电子邮件'),
        ),
        migrations.AlterField(
            model_name='perinfo',
            name='perId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户账号'),
        ),
    ]
